### PR TITLE
Make /proc/devices parser more robust (fix #297)

### LINKED ISSUE #297: `createNvCapDevice()`: may create `/dev/nvidia-caps/nvidia-cap<xxx>` with bad major number
In `createNvCapDevice()` we [read](https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/nvlib.go#L348) the host's `/proc/devices` file in order to obtain the `major` and `minor` device number of the character device called `nvidia-caps`.

Parsing is done by https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/nvlib.go#L228

On an example host, `/proc/devices` may look like:
```
$ cat /proc/devices
Character devices:
  1 mem
<snip>
234 nvidia-caps
235 nvidia-caps-imex-channels
236 nvme-generic
<snip>
504 NVDA2004:00
<snip>

Block devices:
  7 loop
<snip>
```

Current parser code may leave the parsing loop early when a device is present that contains a colon in its name (as in case of `NVDA2004:00` in the example output above):

https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/nvlib.go#L247

In that case, we [return](https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/nvlib.go#L269C2-L269C26)

```
-1, scanner.Err()
```
whereas `-1` is what the caller reads a major number, and `scanner.Err()` is not an error (but `nil`) because scanning (reading the file) did not result in any I/O error or other error.

About `scanner.Err()`:

> Err returns the first non-EOF error that was encountered by the [Scanner](https://pkg.go.dev/bufio#Scanner).

(https://pkg.go.dev/bufio#Scanner.Err)

Consequently, this error handler does _not_ hit in:
```
	major, err := l.getDeviceMajor(nvidiaCapsDeviceName)
	if err != nil {
		return nil, fmt.Errorf("error getting device major: %w", err)
	}
```
and we continue processing `-1` as major number.

A signed integer is often represented as "two's complement" in memory. In that case the bitwise representation of -1 is all ones:

> in two’s complement if all the bits of an integer are 1, then the integer is equal to −1, regardless of how many bits there are

In `createNvCapDevice()` we then [create](https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/nvlib.go#L356) a dev node with a major number of `-1`.  As explained, all bits are set as `1`, i.e. all bytes have value `F` in hex notation.

That is why on the created dev node, `stat` reports the device major as `fff`:
```
# stat /dev/nvidia-caps/nvidia-cap4323 
...
Device: 5h/5d	Inode: 2678        Links: 1     Device type: fff,10e3
...
```
`fff` is 4095 in decimal, so `ls` reports:
```
# ls -la /dev/nvidia-caps
...
cr--------  1 root root 4095, 4323 Mar 25 20:34 nvidia-cap4323
```

As this value is wrong (not the expected / correct device major number), IMEX daemon startup after all fails with a permission error:

> [Mar 25 2025 17:06:27] [ERROR] [tid 38] Failed to acquire required permissions to access driver. If you are running nvidia-imex from a non-root context, make sure required NVIDIA GPU driver capability file permissions are assigned as referenced in user guide.

(also see related issue https://github.com/NVIDIA/k8s-dra-driver-gpu/issues/295#issuecomment-2751970858).

This is a beautiful text-parsing and error handling bug. As of the nature of per-host individual contents of `/proc/devices`, the problem may be rare (does not appear on every host).

### PR DESCRIPTION
**Pull request by jgehrcke**
This is a patch for #297 which tries to take precise control of looking for the match in the expected section of the /proc/devices file contents.

I tested this function in isolation on a 'challenging' node, and it returns data as expected:
```
$ sudo docker run -v $(pwd)/yo.go:/yo.go golang go run /yo.go
234 <nil>
```

### CODE REVIEW

**Comment by jgehrcke** [comment]
We get this code quality warning:

> Incorrect conversion of an integer with architecture-dependent bit size from  to a lower bit size type uint32 without an upper bound check.

Fair enough. We have type `int` everywhere (which often is 64-bit), and then in `dev := unix.Mkdev(uint32(major), uint32(channel))) we "ignorantly" convert to uint32. That's what the complaint is about, and it makes a bit of sense. I will try to mess with the types to resolve this. The upper bound check for a 32-bit signed integer can be performed with `strconv.ParseInt(value, 10, 32)`. The upper bound for a 32-bit UNsigned integer is higher.

**Comment by jgehrcke** [comment]
I have btw visualized and tested the regular expression here: https://regex101.com/r/WaHkdK/1

I've also given it a bit of a challenging probe, and with the green highlight we see that it extracts the data in question despite a number of distractions:

image

**Comment by jgehrcke** [comment]
Tested on Luna, which has limited signal: IMEX daemon not meant to start up, and code path is [not visted](https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/085c1797e7ce52425a4b61d200c50dfbb5ad56c4/cmd/compute-domain-kubelet-plugin/device_state.go#L382):

```
	// Only prepare files to inject to the daemon if IMEX is supported.
	if s.computeDomainManager.cliqueID != "" {
		// Parse the device node info for the fabic-imex-mgmt nvcap.
		nvcapDeviceInfo, err := s.nvdevlib.parseNVCapDeviceInfo(nvidiaCapFabricImexMgmtPath)
		if err != nil {
			return nil, fmt.Errorf("error parsing nvcap device info for fabic-imex-mgmt: %w", err)
		}

		// Create the device node for the fabic-imex-mgmt nvcap.
		if err := s.nvdevlib.createNvCapDevice(nvidiaCapFabricImexMgmtPath); err != nil {
			return nil, fmt.Errorf("error creating nvcap device for fabic-imex-mgmt: %w", err)
		}
```

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 1]
```diff
@@ -225,48 +226,46 @@ func (l deviceLib) getImexChannelCount() (int, error) {
...
-				foundCharDevices = true
-			}
-			// Continue to the next line, regardless
-			continue
-		}
+	// Expect precisely one match: first element is the total match, second
+	// element corresponds to first capture group within that match (i.e., the
+	// number of interest).
+	matches := re.FindStringSubmatch(string(data))
+	if len(matches) != 2 {
```
[the remark this answers is not in the document]
Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:251]: Thankz Copilot. We're good here :).

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 2]
```diff
@@ -225,48 +226,46 @@ func (l deviceLib) getImexChannelCount() (int, error) {
 	return 2048, nil
 }
 
+// Search for an "<integer> <name>" occurrence in the "Character devices"
+// section of the /proc/devices file. Return the integer.
```
Comment (ArangoGutierrez) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:230]: Funcs[¶](https://tip.golang.org/doc/comment#func)
A function’s doc comment should explain what the function returns or, for functions called for side effects, what it does. Named parameters and results can be referred to directly in the comment, without any special syntax like backquotes. (A consequence of this convention is that names like a, which might be mistaken for ordinary words, are typically avoided.) For example:

package strconv

// Quote returns a double-quoted Go string literal representing s.
// The returned string uses Go escape sequences (\t, \n, \xFF, \u0100)
// for control characters and non-printable characters as defined by IsPrint.
func Quote(s string) string {
    ...
}
And:

package os

// Exit causes the current program to exit with the given status code.
// Conventionally, code zero indicates success, non-zero an error.
// The program terminates immediately; deferred functions are not run.
//
// For portability, the status code should be in the range [0, 125].
func Exit(code int) {
    ...
}


see more at https://tip.golang.org/doc/comment

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 2 above)
Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:230]: OK, what is the specific suggestion here?

> A function’s doc comment should explain what the function returns or, for functions called for side effects, what it does.

The comment does that, I think.

Comment (ArangoGutierrez) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:230]: the comment must start with the func name

Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go]: > the comment must start with the func name

Okay. I changed this, squashed, force-pushed.

Note that in terms of communication and 'truth-seeking', I have remarks:

That aspect was not mentioned in the text you quoted above :) It's also not explicitly said in the doc you linked. I get it, the examples support that idea.

https://stackoverflow.com/questions/35591301/function-name-in-comment is about that topic. There, they quote 

> The first sentence should be a one-sentence summary that starts with the name being declared.

which at some point was part of https://go.dev/doc/effective_go#commentary.

It is not there anymore, today. Probably the removal was a deliberate choice.

**Review by ArangoGutierrez — APPROVED** [review]

**Comment by jgehrcke** [comment]
Thanks, @ArangoGutierrez.

Let's get this in and get going with testing.
